blueprint:
  name: "Hue Gateway - Philips Hue Dimmer Switch - Custom Actions"
  description: Freely customizable actions for Philips Hue Dimmer Switch buttons.
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
              manufacturer: Signify Netherlands B.V.
              model: "Hue dimmer switch (RWL021)"
            - integration: hue
              manufacturer: Signify Netherlands B.V.
              model: "Hue dimmer switch (RWL022)"
    on_press:
      name: Button 1 (ON) press actions
      default: []
      selector:
        action: {}
    on_hold:
      name: Button 1 (ON) hold actions
      default: []
      selector:
        action: {}
    up_press:
      name: Button 2 (UP) press actions
      default: []
      selector:
        action: {}
    up_hold:
      name: Button 2 (UP) hold actions
      default: []
      selector:
        action: {}
    down_press:
      name: Button 3 (DOWN) press actions
      default: []
      selector:
        action: {}
    down_hold:
      name: Button 3 (DOWN) hold actions
      default: []
      selector:
        action: {}
    off_press:
      name: Button 4 (OFF) press actions
      default: []
      selector:
        action: {}
    off_hold:
      name: Button 4 (OFF) hold actions
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input remote

action:
  - variables:
      type: "{{ trigger.event.data.type }}"
      subtype: "{{ trigger.event.data.subtype }}"
  - choose:
      - conditions:
          - "{{ type == 'short_release' }}"
          - "{{ subtype == 1 }}"
        sequence: !input on_press
      - conditions:
          - "{{ type == 'repeat' }}"
          - "{{ subtype == 1 }}"
        sequence: !input on_hold
      - conditions:
          - "{{ type == 'short_release' }}"
          - "{{ subtype == 2 }}"
        sequence: !input up_press
      - conditions:
          - "{{ type == 'repeat' }}"
          - "{{ subtype == 2 }}"
        sequence: !input up_hold
      - conditions:
          - "{{ subtype == 3 }}"
          - "{{ type == 'short_release' }}"
        sequence: !input down_press
      - conditions:
          - "{{ subtype == 3 }}"
          - "{{ type == 'repeat' }}"
        sequence: !input down_hold
      - conditions:
          - "{{ subtype == 4 }}"
          - "{{ type == 'short_release' }}"
        sequence: !input off_press
      - conditions:
          - "{{ subtype == 4 }}"
          - "{{ type == 'repeat' }}"
        sequence: !input off_hold